spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    sort:
       cake:
         fields: id,category,name,price
       order:
         fields: state
    filter:
       order:
           fields: client, confectionerId, state
    cake:
       page:
         size: 5
    order:
      page:
        size: 10



